define(function() {
    return function(controller) {
        var ProductGridWc = new kony.ui.FlexContainer({
            "clipBounds": true,
            "isMaster": true,
            "height": "100%",
            "id": "ProductGridWc",
            "isVisible": true,
            "layoutType": kony.flex.FREE_FORM,
            "left": "0dp",
            "skin": "CopyCopyslFbox4",
            "top": "0dp",
            "width": "100%"
        }, {}, {});
        ProductGridWc.setDefaultUnit(kony.flex.DP);
        var segList = new kony.ui.SegmentedUI2({
            "autogrowMode": kony.flex.AUTOGROW_NONE,
            "data": [{
                "imgOne": "konymp_pl_color3.png",
                "imgProduct": "konymp_pl_shoe_1_list.png",
                "imgProductR": "konymp_pl_shoe_2_list.png",
                "imgROne": "konymp_pl_color5.png",
                "imgRThree": "konymp_pl_color4.png",
                "imgRTwo": "konymp_pl_color6.png",
                "imgStar1": "staractive.png",
                "imgStar1R": "staractive.png",
                "imgStar2": "staractive.png",
                "imgStar2R": "staractive.png",
                "imgStar3": "staractive.png",
                "imgStar3R": "staractive.png",
                "imgStar4": "staractive.png",
                "imgStar4R": "staractive.png",
                "imgStar5": "starinactive.png",
                "imgStar5R": "starinactive.png",
                "imgThree": "konymp_pl_color1.png",
                "imgTwo": "konymp_pl_color2.png",
                "lblDescription": "Black Runnig Shoe Description lines",
                "lblDescriptionR": "Black Runnig Shoe Description lines",
                "lblProductName": "T-Rock Men's",
                "lblProductNameR": "Croc Duet Sneakers",
                "lblRate": "$119.95",
                "lblRateR": "$250.00",
                "lblStatus": "Instock for delivery",
                "lblStatusR": "Instock for delivery"
            }, {
                "imgOne": "konymp_pl_color3.png",
                "imgProduct": "konymp_pl_shoe_3_list.png",
                "imgProductR": "konymp_pl_shoe_4_list.png",
                "imgROne": "konymp_pl_color5.png",
                "imgRThree": "konymp_pl_color4.png",
                "imgRTwo": "konymp_pl_color6.png",
                "imgStar1": "staractive.png",
                "imgStar1R": "staractive.png",
                "imgStar2": "staractive.png",
                "imgStar2R": "staractive.png",
                "imgStar3": "staractive.png",
                "imgStar3R": "staractive.png",
                "imgStar4": "staractive.png",
                "imgStar4R": "staractive.png",
                "imgStar5": "starinactive.png",
                "imgStar5R": "starinactive.png",
                "imgThree": "konymp_pl_color1.png",
                "imgTwo": "konymp_pl_color2.png",
                "lblDescription": "Black Runnig Shoe Description lines",
                "lblDescriptionR": "Black Runnig Shoe Description lines",
                "lblProductName": "Roush Leather",
                "lblProductNameR": "Croc Duet Sneakers",
                "lblRate": "$250.00",
                "lblRateR": "$150.90",
                "lblStatus": "Instock for delivery",
                "lblStatusR": "Instock for delivery"
            }, {
                "imgOne": "konymp_pl_color3.png",
                "imgProduct": "konymp_pl_shoe_1_list.png",
                "imgProductR": "konymp_pl_shoe_2_list.png",
                "imgROne": "konymp_pl_color4.png",
                "imgRThree": "konymp_pl_color1.png",
                "imgRTwo": "konymp_pl_color3.png",
                "imgStar1": "staractive.png",
                "imgStar1R": "staractive.png",
                "imgStar2": "staractive.png",
                "imgStar2R": "staractive.png",
                "imgStar3": "staractive.png",
                "imgStar3R": "staractive.png",
                "imgStar4": "staractive.png",
                "imgStar4R": "starinactive.png",
                "imgStar5": "starinactive.png",
                "imgStar5R": "starinactive.png",
                "imgThree": "konymp_pl_color1.png",
                "imgTwo": "konymp_pl_color2.png",
                "lblDescription": "Black Runnig Shoe Description lines",
                "lblDescriptionR": "Black Runnig Shoe Description lines",
                "lblProductName": "T-Rock Men's",
                "lblProductNameR": "Roush Sneaker",
                "lblRate": "$119.95",
                "lblRateR": "$250.00",
                "lblStatus": "Instock for delivery",
                "lblStatusR": "Instock for delivery"
            }],
            "groupCells": false,
            "height": "100%",
            "id": "segList",
            "isVisible": true,
            "left": "0%",
            "needPageIndicator": true,
            "pageOffDotImage": "pageoffdot_1.png",
            "pageOnDotImage": "pageondot_1.png",
            "retainSelection": false,
            "rowFocusSkin": "Copyseg0cbb3b8fed9914e",
            "rowSkin": "Copyseg0a590b2f7aff747",
            "rowTemplate": "CopyCopyflxRow1",
            "scrollingEvents": {},
            "sectionHeaderSkin": "CopysliPhoneSegmentHeader0eb2cf6e11ccc4c",
            "selectionBehavior": constants.SEGUI_DEFAULT_BEHAVIOR,
            "separatorColor": "64646400",
            "separatorRequired": false,
            "separatorThickness": 1,
            "showScrollbars": false,
            "top": "0%",
            "viewType": constants.SEGUI_VIEW_TYPE_TABLEVIEW,
            "widgetDataMap": {
                "CopyCopyflxRow1": "CopyCopyflxRow1",
                "flxBottom": "flxBottom",
                "flxColorOptions": "flxColorOptions",
                "flxColorOptionsR": "flxColorOptionsR",
                "flxLeft": "flxLeft",
                "flxMiddle": "flxMiddle",
                "flxRatingImages": "flxRatingImages",
                "flxRatingImagesR": "flxRatingImagesR",
                "flxRight": "flxRight",
                "imgOne": "imgOne",
                "imgProduct": "imgProduct",
                "imgProductR": "imgProductR",
                "imgROne": "imgROne",
                "imgRThree": "imgRThree",
                "imgRTwo": "imgRTwo",
                "imgStar1": "imgStar1",
                "imgStar1R": "imgStar1R",
                "imgStar2": "imgStar2",
                "imgStar2R": "imgStar2R",
                "imgStar3": "imgStar3",
                "imgStar3R": "imgStar3R",
                "imgStar4": "imgStar4",
                "imgStar4R": "imgStar4R",
                "imgStar5": "imgStar5",
                "imgStar5R": "imgStar5R",
                "imgThree": "imgThree",
                "imgTwo": "imgTwo",
                "lblDescription": "lblDescription",
                "lblDescriptionR": "lblDescriptionR",
                "lblProductName": "lblProductName",
                "lblProductNameR": "lblProductNameR",
                "lblRate": "lblRate",
                "lblRateR": "lblRateR",
                "lblStatus": "lblStatus",
                "lblStatusR": "lblStatusR"
            },
            "width": "100%",
            "zIndex": 1
        }, {
            "padding": [0, 0, 0, 0],
            "paddingInPixel": false
        }, {});
        ProductGridWc.add(segList);
        return ProductGridWc;
    }
})